routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/** frontpage */
Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();
// Route::resource('/operational', 'OperationalController')->middleware('auth');
//CRUD
/**
 * 1. route:get /operational -> controller@index
 * 
 * 2. route:get /operational/create -> controller@create
 * 3. route:post /operational/store -> controller@store
 * 
 * 4. route:get /operational/{id} -> controller@show
 * 
 * 5. route:get /operational/{id}/edit -> controller@edit
 * 6. route:patch/put /operational/{id} -> controller@update
 * 
 * 7. route:delete /operational/{id} -> controller@delete
 */



/** backoffice */
Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace' => 'Backend'], function(){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/revenue', 'RevenueController@index')->name('revenue');
    
    Route::resource('/transaction', 'TransactionController');

    Route::any('/operational/ajax', 'OperationalController@ajax')->name('operational.ajax');
    Route::resource('/operational', 'OperationalController');
});

app/Models/Operational.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Operational extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'price', 'notes', 'purchase_date'
    ];

    protected $dateFormat = 'U';
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    protected $hidden = ['deleted_at'];
}

app/Http/Controllers/Backend/OperationalController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Operational;
use Illuminate\Http\Request;

class OperationalController extends Controller
{
    private $operational;

    public function __construct(Operational $_operational)
    {
        $this->operational = $_operational;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $purchaseDate = $request->purchase_date;
        if($purchaseDate){
            $operationals = $this->operational->where('purchase_date', $purchaseDate)->get();
        }else{
            $operationals = $this->operational->all();
        }

        $purchaseDate = $purchaseDate ?? date('Y-m-d');
        return view('admin/operational/index', compact('operationals', 'purchaseDate'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.operational.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->operational->create([
            'title' => $request->title,
            'price' => $request->price,
            'purchase_date' => $request->purchase_date,
            'notes' => $request->notes,
        ]);

        return redirect(route('operational.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function show(Operational $operational)
    {
        return view('admin.operational.show', compact('operational'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function edit(Operational $operational)
    {
        return view('admin/operational/edit', compact('operational'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $this->operational->where('id', $id)->first();

        $data->title = $request->title;
        $data->price = $request->price;
        $data->notes = $request->notes; 
        $data->purchase_date = $request->purchase_date;
        
        if($data->save()){
            return redirect(route('operational.index'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function destroy(Operational $operational)
    {
        if($operational->delete()){
            return redirect(route('operational.index'));
        }
    }

    /** handle ajax */
    public function ajax(Request $request)
    {
        $data = $this->operational->where('id', $request->id)->first();
        return $data;    
    }
}

resources/views/admin/operational/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col d-flex align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Add New Operational Cost</h6>
                </div>
            </div>
        </div>
        <div class="card-body">
        
            <form action="{{ route('operational.store') }}" method="POST">
                @method('POST')
                @csrf
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Title*</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="title" name="title">
                                    @error('title')
                                        <p class="block-tag">
                                            <small class="badge badge-default badge-danger">{{ $message }}</small>
                                        </p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Price*</label>
                                <div class="col-md-10">
                                    <input type="number" class="form-control" id="price" name="price">
                                    @error('number')
                                        <p class="block-tag">
                                            <small class="badge badge-default badge-danger">{{ $message }}</small>
                                        </p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">notes</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" id="notes" name="notes"></textarea>
                                    @error('notes')
                                        <p class="block-tag">
                                            <small class="badge badge-default badge-danger">{{ $message }}</small>
                                        </p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Purchase Date*</label>
                                <div class="col-md-10">
                                    <input type="date" class="form-control" id="purchase_date" name="purchase_date" value="{{ date('Y-m-d') }}">
                                    @error('purchase_date')
                                        <p class="block-tag">
                                            <small class="badge badge-default badge-danger">{{ $message }}</small>
                                        </p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left"></label>
                                <div class="col-md-10">
                                    <a type="btn" class="btn btn-md btn-secondary" href="{{ route('operational.index') }}">Back</a>
                                    <button type="submit" class="btn btn-md btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

resources/views/admin/operational/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col d-flex align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Operational Cost</h6>
                </div>
            </div>
        </div>
        <div class="card-body">
        
            <form action="{{ route('operational.update', $operational->id) }}" method="POST">
                @method('PUT')
                @csrf
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Title*</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="title" name="title" value="{{ $operational->title }}">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Price*</label>
                                <div class="col-md-10">
                                    <input type="number" class="form-control" id="price" name="price" value="{{ $operational->price }}">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">notes</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" id="notes" name="notes">{{ $operational->notes }}</textarea>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Purchase Date*</label>
                                <div class="col-md-10">
                                    <input type="date" class="form-control" id="purchase_date" name="purchase_date" value="{{ $operational->purchase_date ?? date('Y-m-d') }}">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left"></label>
                                <div class="col-md-10">
                                    <a type="btn" class="btn btn-md btn-secondary" href="{{ route('operational.index') }}">Back</a>
                                    <button type="submit" class="btn btn-md btn-primary">Edit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

resources/views/admin/operational/index.blade.php
@extends('layouts.app', ['title' => 'Operational'])

@section('content')
<div class="container-fluid" id="operational-page" data-ajax-url="{{ route('operational.ajax') }}">
    <script>
        var $lala = @json($lala) 
    </script>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col d-flex align-items-center justify-content-between">
                    <a type="button" class="btn btn-sm btn-primary" href="{{ route('operational.create') }}">Add New</a>
                    
                    <form class="form-inline my-2 my-lg-0">
                        <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> -->
                        <form method="GET" action="{{ route('operational.index') }}">
                            <input type="date" class="form-control" name="purchase_date" value="{{ $purchaseDate }}">
                            <input type="submit" class="btn btn-sm btn-primary" value="filter">
                        </form>
                    </form>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Price</th>
                            <th scope="col">Notes</th>
                            <th scope="col">Purchase Date</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($operationals as $key => $item)
                        <tr>
                            <th scope="row">{{ $key + 1 }}</th>
                            <td>{{ $item->title }}</td>
                            <td>{{ $item->price }}</td>
                            <td>{{ $item->notes }}</td>
                            <td>{{ $item->purchase_date }}</td>
                            <td>
                                <div class="row">
                                    <div class="col-12">
                                        <a type="btn" class="btn btn-sm btn-secondary" href="{{ route('operational.show', $item->id) }}" >show</a>
                                        <a type="btn" class="btn btn-sm btn-secondary showData" id="{{ $item->id }}" >show ajax</a>
                                        <a type="btn" class="btn btn-sm btn-primary" href="{{ route('operational.edit', $item->id) }}">Edit</a>
                                    
                                        <form action="{{ route('operational.destroy', $item->id) }}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <input type="submit" class="btn btn-sm btn-danger" value="delete">
                                        </form>
                                    </div>
                                </div>
                                
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="ajax-container">
    </div>
</div>
@endsection

resources/views/admin/operational/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col d-flex align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Operational Cost</h6>
                </div>
            </div>
        </div>
        <div class="card-body">
        
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Title</label>
                            <div class="col-md-10">
                                <p>{{ $operational->title }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Price</label>
                            <div class="col-md-10">
                                <p>{{ $operational->price }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">notes</label>
                            <div class="col-md-10">
                                <p>{{ $operational->notes }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Purchase Date</label>
                            <div class="col-md-10">
                                <p>{{ $operational->purchase_date }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left"></label>
                            <div class="col-md-10">
                                <a type="btn" class="btn btn-md btn-secondary" href="{{ route('operational.index') }}">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        

        </div>
    </div>
</div>
@endsection