routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/** frontpage */
Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();
// Route::resource('/operational', 'OperationalController')->middleware('auth');
//CRUD
/**
 * 1. route:get /operational -> controller@index
 * 
 * 2. route:get /operational/create -> controller@create
 * 3. route:post /operational/store -> controller@store
 * 
 * 4. route:get /operational/{id} -> controller@show
 * 
 * 5. route:get /operational/{id}/edit -> controller@edit
 * 6. route:patch/put /operational/{id} -> controller@update
 * 
 * 7. route:delete /operational/{id} -> controller@delete
 */



/** backoffice */
Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace' => 'Backend'], function(){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/revenue', 'RevenueController@index')->name('revenue');
    
    Route::resource('/transaction', 'TransactionController');

    Route::any('/operational/ajax', 'OperationalController@ajax')->name('operational.ajax');
    Route::resource('/operational', 'OperationalController');
});

app/Http/Controllers/Backend/TransactionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Transaction;
use App\Models\TransactionDetail;
use App\Models\Product;
use App\Models\Revenue;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreTransactionsRequest;
use App\Http\Requests\UpdateTransactionsRequest;
use Illuminate\Http\Request;
use stdClass;

class TransactionController extends Controller
{
    private $transactions;
    private $products;

    public function __construct(
        Transaction $_transactions,
        Product $_products
    )
    {
        $this->transactions = $_transactions;
        $this->products = $_products;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = $this->transactions->paginate(10);
        return view('admin.transaction.index', compact('transactions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = $this->products->all();
        return view('admin.transaction.add', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreTransactionsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $transactionID = null;
        $date = $request->date ?? date('Y-m-d');
        if(is_array($request->productID) && count($request->productID) > 0)
        {
            /**init transaction model */
            $transaction = new Transaction();
            $transaction->date = $date;
            $transaction->total_selling_price = 0;
            $transaction->total_purchase_price = 0;
            $transaction->profit = 0;
            
            /**create temp data */
            $products = [];
            $transactionDetails = [];
            
            /** handel same ID on transaction & sum qty */
            foreach ($request->productID as $key => $productID) {
                if(isset($products[$productID]))
                {
                    $products[$productID] += $request->productQty[$key] ?? 0;
                }else{
                    $products[$productID] = $request->productQty[$key] ?? 0;
                }
            }

            /** calculate amount fot transaction detail */
            foreach ($products as $productID => $qty) {
                $product = Product::find($productID);
                if($product)
                {
                    /**init transaction details model */
                    $detailsItem = new TransactionDetail();
                    $detailsItem->current_selling_price = $product->selling_price;
                    $detailsItem->current_purchase_price = $product->purchase_price;
                    $detailsItem->quantity = $qty;
                    $detailsItem->product_id = $productID;
                    $detailsItem->subtotal_selling_price = $product->selling_price * $qty;
                    $detailsItem->subtotal_purchase_price = $product->purchase_price * $qty;

                    /**update transaction model value */
                    $transaction->total_selling_price += $detailsItem->subtotal_selling_price;
                    $transaction->total_purchase_price += $detailsItem->subtotal_purchase_price;
                    $transaction->profit += $transaction->total_selling_price - $transaction->total_purchase_price;

                    $transactionDetails[] = $detailsItem;
                }
            }

            /**if there is transaction details, save the model */
            if(count($transactionDetails)>0)
            {
                $transaction->save();
                foreach ($transactionDetails as $key => $item) {
                    $transaction->details()->save($item);
                }
                $transactionID = $transaction->id;

                /**update revenue table */
                $this->updateRevenue(
                    $transaction->date,
                    $transaction->total_selling_price,
                    $transaction->total_purchase_price,
                    $transaction->profit,
                );
            }
        }

        if($transactionID)
        {
            return redirect(route('transaction.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        $this->replicate($transaction);
        return view('admin.transaction.show', compact('transaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateTransactionsRequest  $request
     * @param  \App\Models\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTransactionsRequest $request, Transaction $transaction)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }

    /**generate transaction & detail transaction, by duplicating 1 existing transaction */
    private function replicate($transaction)
    {
        /** we replicate 100 times */
        for ($i=0; $i <1000; $i++) {
            $newTransaction = $transaction->replicate();
            
            /**set diferent date each record */
            $nowInunix = strtotime("+ ". $i ." day");
            $newTransaction->date = date("Y-m-d", $nowInunix);
            $newTransaction->save();

            if($transaction->details->count() > 0){
                foreach ($transaction->details as $key => $item) {
                    # code...
                    $newItem = $item->replicate();
                    $newTransaction->details()->save($newItem);
                }
            }

            /**update revenue table */
            $this->updateRevenue(
                $newTransaction->date,
                $newTransaction->total_selling_price,
                $newTransaction->total_purchase_price,
                $newTransaction->profit,
            );
        }
    }

    /** update revenue table when user create transaction */
    private function updateRevenue($date, $sell, $purchase, $profit)
    {
        $revenue = Revenue::where('date', $date)->first();
        if($revenue)
        {
            $revenue->total_selling_price = $revenue->total_selling_price + $sell;
            $revenue->total_purchase_price = $revenue->total_purchase_price + $purchase;
            $revenue->profit = $revenue->profit + $profit;
        }else{
            $revenue = new Revenue();
            $revenue->total_selling_price = $sell;
            $revenue->total_purchase_price = $purchase;
            $revenue->profit = $profit;
        }
        $revenue->date = $date;

        $revenue->save();
    }
}

resources/views/admin/transaction/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid" id="transactions-add-page">
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col d-flex align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Add New Transactions</h6>
                </div>
            </div>
        </div>
        <div class="card-body">
        
            <form action="{{ route('transaction.store') }}" method="POST">
                @method('POST')
                @csrf
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Transaction Date*</label>
                                <div class="col-md-10">
                                    <input type="date" class="form-control" id="date" name="date" value="{{ date('Y-m-d') }}">
                                    @error('date')
                                        <p class="block-tag">
                                            <small class="badge badge-default badge-danger">{{ $message }}</small>
                                        </p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Item*</label>
                                <div class="col-md-4">
                                    <select id="products" class="form-control">
                                        @foreach ($products as $product)
                                            <option value="{{ $product->id }}" data-price="{{ $product->selling_price }}">{{ $product->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-4">
                                    <input class="form-control" id="quantity" type="number" value="1">
                                </div>
                                <a href="#" id="addDetail"><i class="fa fa-solid fa-plus"></i> more items</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left"></label>
                                <div class="col-md-10">
                                    <table class="table-transactions table table-sm table-hover">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Product Name</th>
                                                <th scope="col">Quantity</th>
                                                <th scope="col">Price</th>
                                                <th scope="col">Subtotal</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left"></label>
                                <div class="col-md-10">
                                    <a type="btn" class="btn btn-md btn-secondary" href="{{ route('transaction.index') }}">Back</a>
                                    <button type="submit" class="btn btn-md btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

resources/views/admin/transaction/index.blade.php
@extends('layouts.app', ['title' => 'Transactions'])

@section('content')
<div class="container-fluid" id="transactions-page">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col d-flex align-items-center justify-content-between">
                    <a type="button" class="btn btn-sm btn-primary" href="{{ route('transaction.create') }}">Add New</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Date</th>
                            <th scope="col">Selling Price</th>
                            <th scope="col">Purchase Price</th>
                            <th scope="col">Profit</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($transactions as $key => $item)
                        <tr>
                            <th scope="row">{{ $key + 1 }}</th>
                            <td>{{ $item->date }}</td>
                            <td>{{ $item->total_selling_price }}</td>
                            <td>{{ $item->total_purchase_price }}</td>
                            <td>{{ $item->profit }}</td>
                            <td></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $transactions->onEachSide(1)->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/transaction/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid" id="transactions-show-page">
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col d-flex align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Transactions Details</h6>
                </div>
            </div>
        </div>
        <div class="card-body">            
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Transaction Date</label>
                                <div class="col-md-10">
                                    <p>{{ $transaction->date }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left"></label>
                                <div class="col-md-10">
                                    <table class="table-transactions table table-sm table-hover">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Product Name</th>
                                                <th scope="col">Quantity</th>
                                                <th scope="col">Price</th>
                                                <th scope="col">Subtotal</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($transaction->details as $key => $detail)
                                            <tr>
                                                <td><p>{{ $key }}</p></td>
                                                <td><p>{{ $detail->product->name }}</p></td>
                                                <td><p>{{ $detail->quantity }}</p></td>
                                                <td><p>{{ $detail->current_selling_price }}</p></td>
                                                <td><p>{{ $detail->subtotal_selling_price }}</p></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Purchase Price</label>
                                <div class="col-md-8">
                                    <p>{{ $transaction->total_purchase_price }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Selling Price</label>
                                <div class="col-md-8">
                                    <p>{{ $transaction->total_selling_price }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left">Profit</label>
                                <div class="col-md-8">
                                    <p>{{ $transaction->profit }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group row">
                                <label class="col-md-2 label-control text-left"></label>
                                
                            </div>
                        </div>
                    </div>
                </div>

        </div>
    </div>
</div>
@endsection